FIGURE_EXPLANATIONS = {
    "actual_vs_predicted.png": {
        "purpose": "Compares held-out actual completion rates against SVR predictions.",
        "how": "Each point is one held-out state-stage-sex row. Points closer to the diagonal line have smaller prediction error.",
        "better": "Closer to the diagonal line is better.",
        "takeaway": "Use this figure to see whether the model follows the general target range and where it misses.",
        "caveat": "Visual fit must still be interpreted with MAE, RMSE, R², and baseline comparison.",
    },
    "actual_vs_predicted_with_error_bands.png": {
        "purpose": "Shows prediction fit with practical percentage-point error bands.",
        "how": "Rows inside the band are closer to the actual completion rate; rows outside the band have larger errors.",
        "better": "More points inside the narrow error bands is better.",
        "takeaway": "Useful for explaining practical tolerance, not only numeric error metrics.",
        "caveat": "A practical band does not imply causal or production-level reliability.",
    },
    "residual_distribution.png": {
        "purpose": "Shows the distribution of actual-minus-predicted residuals.",
        "how": "Positive residuals mean underprediction; negative residuals mean overprediction.",
        "better": "A distribution centered near zero with a narrow spread is better.",
        "takeaway": "Use this to check prediction bias and error spread.",
        "caveat": "Residual patterns are descriptive diagnostics, not causal explanations.",
    },
    "residuals_vs_predicted.png": {
        "purpose": "Checks whether residuals change across the predicted completion-rate range.",
        "how": "Look for systematic patterns rather than random scatter around zero.",
        "better": "Less pattern and residuals closer to zero are better.",
        "takeaway": "This helps identify whether the model struggles at certain prediction ranges.",
        "caveat": "The held-out set is small, so visual patterns should be interpreted cautiously.",
    },
    "chronological_split_timeline.png": {
        "purpose": "Shows the chronological train, validation, test, and forecast-candidate design.",
        "how": "Training years occur before validation and held-out test years.",
        "better": "Validation and test years should be later than training years for next-year prediction.",
        "takeaway": "This supports time-aware evaluation and reduces future-year leakage risk.",
        "caveat": "Few annual years still limit generalisation confidence.",
    },
    "permutation_importance.png": {
        "purpose": "Shows feature influence diagnostics for the selected SVR model.",
        "how": "Larger absolute importance means the model error changed more when that feature was perturbed.",
        "better": "There is no universal better direction; this is an interpretation diagnostic.",
        "takeaway": "Highlights which features the trained model is most sensitive to.",
        "caveat": "Permutation importance is not causal evidence.",
    },
    "permutation_importance_grouped_by_feature_source.png": {
        "purpose": "Groups permutation importance by feature source/type.",
        "how": "Higher total importance means that feature group had larger diagnostic influence for the trained model.",
        "better": "Not a performance metric; use it to understand model reliance.",
        "takeaway": "Shows whether completion history, education capacity, household, demographic, or categorical features dominate.",
        "caveat": "Correlated features can share or distort importance.",
    },
    "error_by_state.png": {
        "purpose": "Shows average prediction error by state.",
        "how": "Higher bars mean larger average absolute error for that state.",
        "better": "Lower error is better.",
        "takeaway": "Use this to identify which states were harder for the model in the held-out year.",
        "caveat": "State-level error from one held-out year should not be overgeneralised.",
    },
    "error_by_stage.png": {
        "purpose": "Shows average prediction error by school stage.",
        "how": "Compare MAE/RMSE across primary, lower secondary, and upper secondary.",
        "better": "Lower error is better.",
        "takeaway": "Shows whether one education stage is harder to predict.",
        "caveat": "Stage patterns should be interpreted with row counts and the test-year context.",
    },
    "error_by_sex.png": {
        "purpose": "Shows average prediction error by sex group.",
        "how": "Compare male and female held-out rows using the same error metric.",
        "better": "Lower error is better.",
        "takeaway": "Shows whether prediction errors differ between male and female rows.",
        "caveat": "This is an evaluation diagnostic, not a causal sex-effect analysis.",
    },
    "svr_tolerance_coverage.png": {
        "purpose": "Shows the percentage of predictions within practical error bands.",
        "how": "Higher percentages mean more predictions fall within the selected tolerance band.",
        "better": "Higher coverage is better.",
        "takeaway": "This translates model error into practical planning language.",
        "caveat": "Tolerance bands are descriptive thresholds, not formal confidence intervals.",
    },
    "expanded_model_metric_heatmap.png": {
        "purpose": "Compares models and baselines across multiple metrics.",
        "how": "Use the metric direction guide: lower is better for MAE/RMSE/Median AE, higher is better for R².",
        "better": "Depends on the metric column.",
        "takeaway": "Shows whether SVR improves over simple baselines and benchmark models.",
        "caveat": "Ranking must be based on the same held-out test rows.",
    },
    "expanded_mae_comparison.png": {
        "purpose": "Compares Mean Absolute Error across models and baselines.",
        "how": "Each bar is test MAE in percentage points.",
        "better": "Lower is better.",
        "takeaway": "Shows which method has the lowest average absolute error.",
        "caveat": "Use RMSE and R² as supporting checks, not only MAE.",
    },
    "expanded_rmse_comparison.png": {
        "purpose": "Compares Root Mean Squared Error across models and baselines.",
        "how": "Each bar is test RMSE in percentage points and penalizes large misses.",
        "better": "Lower is better.",
        "takeaway": "Shows which method reduces larger prediction errors.",
        "caveat": "RMSE can be strongly affected by a few large-error rows.",
    },
    "svr_improvement_over_baselines.png": {
        "purpose": "Shows SVR improvement over baseline methods.",
        "how": "Positive improvement means SVR has lower error than the baseline.",
        "better": "Larger positive improvement is better.",
        "takeaway": "Shows whether SVR adds value beyond simple rules.",
        "caveat": "A model can improve error and still have weak R².",
    },
    "target_distribution_histogram.png": {
        "purpose": "Shows the distribution of the numeric target.",
        "how": "The x-axis is completion rate and the y-axis is row frequency.",
        "better": "No better direction; it is a data understanding figure.",
        "takeaway": "Helps verify that the target is numeric regression, not classification.",
        "caveat": "Completion rates can exceed 100 due to source-data definitions and should not be clipped without justification.",
    },
}


def explain(filename: str) -> dict:
    return FIGURE_EXPLANATIONS.get(filename, {
        "purpose": "Notebook visual evidence for the selected workflow section.",
        "how": "Read the figure title, axes, legend, and associated table output for context.",
        "better": "Depends on the metric shown. Lower is better for error metrics; higher is better for coverage and R².",
        "takeaway": "Use the chart as supporting evidence together with the saved tables and page interpretation.",
        "caveat": "Do not interpret visual patterns as causal unless a causal design was used.",
    })

FIGURE_EXPLANATIONS.update({
    "model_metric_leaderboard.png": {
        "purpose": "Summarises the held-out model ranking across core regression metrics.",
        "how": "Compare SVR and RandomForestRegressor using MAE, RMSE, R², and Median AE.",
        "better": "Lower MAE/RMSE/Median AE is better; higher R² is better.",
        "takeaway": "SVR is stronger than RF in the current comparison.",
        "caveat": "Both models have negative R², so this is a comparative result, not high-accuracy evidence.",
    },
    "model_metric_leaderboard_mae.png": {
        "purpose": "Shows the model leaderboard by MAE.",
        "how": "Read lower bars as smaller average absolute error in percentage points.",
        "better": "Lower is better.",
        "takeaway": "SVR has lower MAE than RF.",
        "caveat": "Use RMSE and R² as supporting checks.",
    },
    "model_metric_leaderboard_rmse.png": {
        "purpose": "Shows the model leaderboard by RMSE.",
        "how": "Read lower bars as smaller large-error-penalised prediction error.",
        "better": "Lower is better.",
        "takeaway": "SVR has lower RMSE than RF.",
        "caveat": "RMSE can be affected by a small number of large errors.",
    },
    "baseline_mae_improvement_comparison.png": {
        "purpose": "Shows model improvement against baseline methods using MAE.",
        "how": "Positive improvement means the model has lower MAE than the baseline.",
        "better": "Larger positive improvement is better.",
        "takeaway": "SVR improves over the compared baselines more consistently than RF.",
        "caveat": "Baseline availability and definitions should be read from the saved tables.",
    },
    "row_level_winner_summary.png": {
        "purpose": "Shows how many held-out rows are won by each model.",
        "how": "A row is won by the model with lower absolute error.",
        "better": "More row wins is better.",
        "takeaway": "SVR wins most held-out rows.",
        "caveat": "Row-level wins should be interpreted together with aggregate metrics.",
    },
    "tolerance_comparison.png": {
        "purpose": "Compares practical tolerance coverage between SVR and RF.",
        "how": "Higher percentages mean more predictions are within the selected error band.",
        "better": "Higher is better.",
        "takeaway": "SVR has better tolerance coverage than RF.",
        "caveat": "Tolerance bands are descriptive thresholds, not confidence intervals.",
    },
    "residual_bias_comparison.png": {
        "purpose": "Compares residual bias between SVR and RF.",
        "how": "Residual is actual minus predicted; positive residuals indicate underprediction.",
        "better": "Mean residual closer to zero is better.",
        "takeaway": "Both models underpredict, but RF underpredicts more strongly.",
        "caveat": "Residual direction does not replace MAE/RMSE evaluation.",
    },
    "error_by_state_comparison.png": {
        "purpose": "Compares model error by state.",
        "how": "Each state shows model error values for SVR and RF.",
        "better": "Lower error is better.",
        "takeaway": "SVR has lower error in most states.",
        "caveat": "State-level results come from one held-out input year.",
    },
    "error_by_stage_comparison.png": {
        "purpose": "Compares model error by school stage.",
        "how": "Compare primary, secondary_lower, and secondary_upper groups.",
        "better": "Lower error is better.",
        "takeaway": "SVR is better across all stages in the current output.",
        "caveat": "Stage errors should not be treated as causal explanations.",
    },
    "error_by_sex_comparison.png": {
        "purpose": "Compares model error by sex group.",
        "how": "Compare male and female held-out rows.",
        "better": "Lower error is better.",
        "takeaway": "SVR is better for both sex groups.",
        "caveat": "This is an evaluation subgroup analysis only.",
    },
    "top_feature_influence_comparison.png": {
        "purpose": "Compares top feature influence diagnostics across models.",
        "how": "Higher importance indicates stronger diagnostic influence within the fitted model.",
        "better": "There is no accuracy direction; this is interpretation evidence.",
        "takeaway": "Completion-history signals are important in both models.",
        "caveat": "Feature influence is not causal evidence.",
    },
    "feature_influence_support_vector_regression_permutation_importance.png": {
        "purpose": "Shows SVR permutation importance from the comparison notebook.",
        "how": "Larger values indicate larger change in prediction error when the feature is perturbed.",
        "better": "Not a performance metric.",
        "takeaway": "SVR is sensitive to completion-history and contextual features.",
        "caveat": "Permutation importance can be affected by correlated features.",
    },
    "feature_influence_randomforestregressor_native_feature_importance.png": {
        "purpose": "Shows native RandomForestRegressor feature importance.",
        "how": "Higher native importance means the tree ensemble used that feature more strongly in splits.",
        "better": "Not a performance metric.",
        "takeaway": "RF relies heavily on completion-history features.",
        "caveat": "Native RF importance can be biased by correlated or high-cardinality features.",
    },
    "feature_influence_randomforestregressor_permutation_importance.png": {
        "purpose": "Shows RF permutation importance from the comparison notebook.",
        "how": "Larger values indicate greater diagnostic effect on model score when perturbed.",
        "better": "Not a performance metric.",
        "takeaway": "RF sensitivity is strongest around completion-history and categorical context.",
        "caveat": "Permutation importance is diagnostic, not causal.",
    },
    "ai_demonstrator_comparison.png": {
        "purpose": "Visualises one same-row AI demonstrator comparison between SVR and RF.",
        "how": "Compare each model prediction with the actual next-year completion rate.",
        "better": "The prediction closer to the actual value is better for this row.",
        "takeaway": "SVR is closer for the selected demonstrator row.",
        "caveat": "One demonstrator row does not replace full held-out evaluation.",
    },
})
