FIGURE_EXPLANATIONS = {
    "actual_vs_predicted.png": {
        "purpose": "Compares held-out actual completion rates against SVR predictions.",
        "how": "Each point is one held-out state-stage-sex row. Points closer to the diagonal line have smaller prediction error.",
        "better": "Closer to the diagonal line is better.",
        "takeaway": "Use this figure to see whether the model follows the general target range and where it misses.",
        "caveat": "Visual fit must still be interpreted with MAE, RMSE, R², and baseline comparison.",
    },
    "actual_vs_predicted_with_error_bands.png": {
        "purpose": "Shows prediction fit with practical percentage-point error bands.",
        "how": "Rows inside the band are closer to the actual completion rate; rows outside the band have larger errors.",
        "better": "More points inside the narrow error bands is better.",
        "takeaway": "Useful for explaining practical tolerance, not only numeric error metrics.",
        "caveat": "A practical band does not imply causal or production-level reliability.",
    },
    "residual_distribution.png": {
        "purpose": "Shows the distribution of actual-minus-predicted residuals.",
        "how": "Positive residuals mean underprediction; negative residuals mean overprediction.",
        "better": "A distribution centered near zero with a narrow spread is better.",
        "takeaway": "Use this to check prediction bias and error spread.",
        "caveat": "Residual patterns are descriptive diagnostics, not causal explanations.",
    },
    "residuals_vs_predicted.png": {
        "purpose": "Checks whether residuals change across the predicted completion-rate range.",
        "how": "Look for systematic patterns rather than random scatter around zero.",
        "better": "Less pattern and residuals closer to zero are better.",
        "takeaway": "This helps identify whether the model struggles at certain prediction ranges.",
        "caveat": "The held-out set is small, so visual patterns should be interpreted cautiously.",
    },
    "chronological_split_timeline.png": {
        "purpose": "Shows the chronological train, validation, test, and forecast-candidate design.",
        "how": "Training years occur before validation and held-out test years.",
        "better": "Validation and test years should be later than training years for next-year prediction.",
        "takeaway": "This supports time-aware evaluation and reduces future-year leakage risk.",
        "caveat": "Few annual years still limit generalisation confidence.",
    },
    "permutation_importance.png": {
        "purpose": "Shows feature influence diagnostics for the selected SVR model.",
        "how": "Larger absolute importance means the model error changed more when that feature was perturbed.",
        "better": "There is no universal better direction; this is an interpretation diagnostic.",
        "takeaway": "Highlights which features the trained model is most sensitive to.",
        "caveat": "Permutation importance is not causal evidence.",
    },
    "permutation_importance_grouped_by_feature_source.png": {
        "purpose": "Groups permutation importance by feature source/type.",
        "how": "Higher total importance means that feature group had larger diagnostic influence for the trained model.",
        "better": "Not a performance metric; use it to understand model reliance.",
        "takeaway": "Shows whether completion history, education capacity, household, demographic, or categorical features dominate.",
        "caveat": "Correlated features can share or distort importance.",
    },
    "error_by_state.png": {
        "purpose": "Shows average prediction error by state.",
        "how": "Higher bars mean larger average absolute error for that state.",
        "better": "Lower error is better.",
        "takeaway": "Use this to identify which states were harder for the model in the held-out year.",
        "caveat": "State-level error from one held-out year should not be overgeneralised.",
    },
    "error_by_stage.png": {
        "purpose": "Shows average prediction error by school stage.",
        "how": "Compare MAE/RMSE across primary, lower secondary, and upper secondary.",
        "better": "Lower error is better.",
        "takeaway": "Shows whether one education stage is harder to predict.",
        "caveat": "Stage patterns should be interpreted with row counts and the test-year context.",
    },
    "error_by_sex.png": {
        "purpose": "Shows average prediction error by sex group.",
        "how": "Compare male and female held-out rows using the same error metric.",
        "better": "Lower error is better.",
        "takeaway": "Shows whether prediction errors differ between male and female rows.",
        "caveat": "This is an evaluation diagnostic, not a causal sex-effect analysis.",
    },
    "svr_tolerance_coverage.png": {
        "purpose": "Shows the percentage of predictions within practical error bands.",
        "how": "Higher percentages mean more predictions fall within the selected tolerance band.",
        "better": "Higher coverage is better.",
        "takeaway": "This translates model error into practical planning language.",
        "caveat": "Tolerance bands are descriptive thresholds, not formal confidence intervals.",
    },
    "expanded_model_metric_heatmap.png": {
        "purpose": "Compares models and baselines across multiple metrics.",
        "how": "Use the metric direction guide: lower is better for MAE/RMSE/Median AE, higher is better for R².",
        "better": "Depends on the metric column.",
        "takeaway": "Shows whether SVR improves over simple baselines and benchmark models.",
        "caveat": "Ranking must be based on the same held-out test rows.",
    },
    "expanded_mae_comparison.png": {
        "purpose": "Compares Mean Absolute Error across models and baselines.",
        "how": "Each bar is test MAE in percentage points.",
        "better": "Lower is better.",
        "takeaway": "Shows which method has the lowest average absolute error.",
        "caveat": "Use RMSE and R² as supporting checks, not only MAE.",
    },
    "expanded_rmse_comparison.png": {
        "purpose": "Compares Root Mean Squared Error across models and baselines.",
        "how": "Each bar is test RMSE in percentage points and penalizes large misses.",
        "better": "Lower is better.",
        "takeaway": "Shows which method reduces larger prediction errors.",
        "caveat": "RMSE can be strongly affected by a few large-error rows.",
    },
    "svr_improvement_over_baselines.png": {
        "purpose": "Shows SVR improvement over baseline methods.",
        "how": "Positive improvement means SVR has lower error than the baseline.",
        "better": "Larger positive improvement is better.",
        "takeaway": "Shows whether SVR adds value beyond simple rules.",
        "caveat": "A model can improve error and still have weak R².",
    },
    "target_distribution_histogram.png": {
        "purpose": "Shows the distribution of the numeric target.",
        "how": "The x-axis is completion rate and the y-axis is row frequency.",
        "better": "No better direction; it is a data understanding figure.",
        "takeaway": "Helps verify that the target is numeric regression, not classification.",
        "caveat": "Completion rates can exceed 100 due to source-data definitions and should not be clipped without justification.",
    },
}


def explain(filename: str) -> dict:
    return FIGURE_EXPLANATIONS.get(filename, {
        "purpose": "Notebook visual evidence for the selected workflow section.",
        "how": "Read the figure title, axes, legend, and associated table output for context.",
        "better": "Depends on the metric shown. Lower is better for error metrics; higher is better for coverage and R².",
        "takeaway": "Use the chart as supporting evidence together with the saved tables and page interpretation.",
        "caveat": "Do not interpret visual patterns as causal unless a causal design was used.",
    })
